/**/**:
  ros__parameters:
    feature_extract_enable: false
    point_filter_num: 3
    max_iteration: 10
    filter_size_surf: 0.8
    filter_size_map: 0.8
    cube_side_length: 200.0
    runtime_pos_log_enable: false
    map_file_path: "./test.pcd"

    common:
      time_sync_en: false # ONLY turn on when external time synchronization is really not possible
      time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

    preprocess:
      lidar_type: 0 # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for any other pointcloud input
      scan_line: 16
      blind: 0.15
      timestamp_unit: 3
      scan_rate: 10

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 360.0
      det_range: 30.0
      extrinsic_est_en: true # true: enable the online estimation of IMU-LiDAR extrinsic
      extrinsic_T: [-0.0, -0.0, 0.0]
      extrinsic_R:
        [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0] # [r11, r12, r13, r21, r22, r23, r31, r32, r33]

    publish:
      path_en: true # true: publish Path
      effect_map_en: true # true: publish Effects
      map_en: true # true: publish Map cloud
      scan_publish_en: true # false: close all the point cloud output
      dense_publish_en: true # false: low down the points number in a global-frame point clouds scan.
      scan_bodyframe_pub_en: true # true: output the point cloud scans in IMU-body-frame

    pcd_save:
      pcd_save_en: false
      interval: -1 # how many LiDAR frames saved in each pcd file;
        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
        
    imu_in_gravity_unit: false # true: the IMU linear acceleration is in gravity unit (g), false: in m/s^2
    velocity_in_body_frame: true # true: the velocity is in body frame, false: in world frame

    transform:
        enable: true # true: publish the TF transform between lidar_frame and world_frame, false: do not publish
        enable_imu: true # true: publish the TF transform between lidar_frame and world_frame, false: do not publish
        fcu_frame: "uav1/fcu"
        world_frame: "uav1/world"
        lidar_frame: "uav1/livox_lidar"
        imu_frame: "uav1/livox_imu"
